[package]
name = "spammer"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

description = "Creates empty files with random names"

[dependencies]
anyhow = "1.0.31"
rand = "0.7.3"
rayon = "1.3.1"
structopt = "0.3.14"
